
Running evaluation for dataset: fiq
Traceback (most recent call last):
  File "D:\Documents 2.0\5th semester\computer vision\Vision Project\ZS-CIR\testbyfig.py", line 154, in <module>
    main(cfg) # Calls the modified main function
    ^^^^^^^^^
  File "D:\Documents 2.0\5th semester\computer vision\Vision Project\ZS-CIR\testbyfig.py", line 26, in main
    model = get_model(cfg)
            ^^^^^^^^^^^^^^
  File "D:\Documents 2.0\5th semester\computer vision\Vision Project\ZS-CIR\utils.py", line 15, in get_model
    model = TransAgg(cfg)
            ^^^^^^^^^^^^^
  File "D:\Documents 2.0\5th semester\computer vision\Vision Project\ZS-CIR\model\model.py", line 17, in __init__
    self.pretrained_model, self.preprocess = clip.load("D:/Documents 2.0/5th semester/computer vision/Vision Project/ViT-B-32.pt", device=cfg.device, jit=False)
                                             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\Documents 2.0\5th semester\computer vision\Vision Project\ZS-CIR\model\clip\clip.py", line 124, in load
    raise RuntimeError(f"Model {name} not found; available models = {available_models()}")
RuntimeError: Model D:/Documents 2.0/5th semester/computer vision/Vision Project/ViT-B-32.pt not found; available models = ['RN50', 'RN101', 'RN50x4', 'RN50x16', 'RN50x64', 'ViT-B/32', 'ViT-B/16', 'ViT-L/14', 'ViT-L/14@336px']